package com.glodon.materialdb.mybatis.models;

import java.io.Serializable;

public class MaterialRequirementPlan implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_requirement_plan.id
     *
     * @mbggenerated
     */

    private static final long serialVersionUID = -1L;
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_requirement_plan.material_id
     *
     * @mbggenerated
     */
    private Integer materialId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_requirement_plan.material_name
     *
     * @mbggenerated
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_requirement_plan.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_requirement_plan.id
     *
     * @return the value of material_requirement_plan.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_requirement_plan.id
     *
     * @param id the value for material_requirement_plan.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_requirement_plan.material_id
     *
     * @return the value of material_requirement_plan.material_id
     *
     * @mbggenerated
     */
    public Integer getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_requirement_plan.material_id
     *
     * @param materialId the value for material_requirement_plan.material_id
     *
     * @mbggenerated
     */
    public void setMaterialId(Integer materialId) {
        this.materialId = materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_requirement_plan.material_name
     *
     * @return the value of material_requirement_plan.material_name
     *
     * @mbggenerated
     */
    public String getMaterialName() {
        return materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_requirement_plan.material_name
     *
     * @param materialName the value for material_requirement_plan.material_name
     *
     * @mbggenerated
     */
    public void setMaterialName(String materialName) {
        this.materialName = materialName == null ? null : materialName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_requirement_plan.remark
     *
     * @return the value of material_requirement_plan.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_requirement_plan.remark
     *
     * @param remark the value for material_requirement_plan.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    @Override
    public String toString() {
        return "MaterialRequirementPlan{" +
                "id=" + id +
                ", materialId=" + materialId +
                ", materialName='" + materialName + '\'' +
                ", remark='" + remark + '\'' +
                '}';
    }
}